name: cameratraps-classifier

channels:
- defaults
- conda-forge
- comet_ml

dependencies:
- python>=3.7, <=3.7.6

# - cpuonly  # for CPU only
- cudatoolkit=11.3  # for GPU

- comet_ml

# from defaults channel
- Pillow
- humanfriendly
- ipywidgets
- jsonpickle  # used by run_detector_batch.py
- jupyterlab
- matplotlib
- mypy
- nb_conda_kernels
- networkx  # used for taxonomy graph
- numpy
- openpyxl  # used by taxonomy_mapping/species_by_dataset.py
- pandas
- progressbar2  # used by ai4eutils (which is called by taxonomy-mapping code)
- pylint
- python-graphviz  # used for taxonomy visualization
- scikit-learn
- seaborn
- tqdm
- xlrd  # for pandas Excel support, needed by taxonomy_mapping/process_species_by_dataset
- pip
- python-dotenv

# from conda-forge
# faster Pillow replacement for torchvision; Linux-only, see README for information
# - accimage      

# Some packages or versions are only available from PyPI
# These may require GCC to be installed
- pip:
  - azure-storage-blob>  # require v12.5.0 for BlobClient.exists()

  # SIMD acceleration for Pillow.  Linux-only, see README for information.
  - pillow-simd

  # conda (defaults channel) tends to lag PyPI for TensorFlow-related packages
  - tensorboard

  # TODO: this doesn't work. Figure out how to do the following: 
  # pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
  # - torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
  # - torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html
  # - torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
