# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
seed: 32678456782 # random number generator seed (long integer value)
device: 'cuda:0'
num_workers: 20 # number of CPU cores that are allocated to support (load images) to the GPU

# dataset parameters
data_root: /home/nrindlaub/animl-ml/classification/data/processed/animl
crops_dir: crops
num_classes: 98

# training hyperparameters
image_size: [224, 224]
num_epochs: 200
batch_size: 1024
learning_rate: 0.001
weight_decay: 0.001